version: "3.9"
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    restart: unless-stopped
    volumes:
      - /opt/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    network_mode: host
  mosquitto:
      container_name: mosquitto
      image: eclipse-mosquitto:latest
      restart: unless-stopped
      volumes:
        - /opt/mosquitto:/mosquitto
      ports:
        - 1883:1883
        - 9001:9001  
      command: "mosquitto -c /mosquitto-no-auth.conf"
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - /opt/zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    environment:
      - TZ=Australia/Sydney
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    user: "1000:1000"
    group_add:
      - dialout